### ISSUE TITLE
So many issues

### ISSUE THREAD

**Issue by StevenC365** [OfficeDev/microsoft-teams-apps-requestateam#6] opened 2020-05-02 18:57 UTC
Sorry, had a really tough time completing the install, here's what I found and resolved

1. Script failed at the PnPTemplate, even though the current PnPPowershell had just been installed. I think it needs a new PS Session after installed. Once I sorted it I could re-run the script.
2. After installing the powerapp, when opening it the O365 user connector would not authenticate, I added it to another app which worked, then it would work in the imported powerapp.
3. For some reason the runbook wouldn't work, again PnP failing to get a token. It seems that the client secret was not correct, maybe because the initial script ran more than once? I regenerated a client secret and applied it to the runbook and in the logic app.
4. In the powerapp the controls to select owners wouldn't work, the IsSearchable property was set to false and had to be changes to true on all controls.

**Comment by alexc-MSFT** [comment] 2020-05-04 08:56
> Sorry, had a really tough time completing the install, here's what I found and resolved
> 
> 1. Script failed at the PnPTemplate, even though the current PnPPowershell had just been installed. I think it needs a new PS Session after installed. Once I sorted it I could re-run the script.
> 2. After installing the powerapp, when opening it the O365 user connector would not authenticate, I added it to another app which worked, then it would work in the imported powerapp.
> 3. For some reason the runbook wouldn't work, again PnP failing to get a token. It seems that the client secret was not correct, maybe because the initial script ran more than once? I regenerated a client secret and applied it to the runbook and in the logic app.
> 4. In the powerapp the controls to select owners wouldn't work, the IsSearchable property was set to false and had to be changes to true on all controls.

Thanks for reporting these Steven, I will investigate and report back.

**Comment by alexc-MSFT** [comment] 2020-05-07 14:56
@StevenC365 regarding point 4, we have confirmed this seems to be a bug with Power Apps and have sent this over to the appropriate people.

**Comment by alexc-MSFT** [comment] 2020-05-07 15:07
@audrieMSFT FYI

**Comment by alexc-MSFT** [comment] 2020-05-21 09:11
Closing for now as most of these have been fixed and the OOTB Power Apps bug has been reported.

**Closed by alexc-MSFT** 2020-05-21 09:11 UTC
