### ISSUE TITLE
Logic App Run Failed - Set SiteExists variable

### ISSUE THREAD

**Issue by neimadpc** [OfficeDev/microsoft-teams-apps-requestateam#30] opened 2020-05-19 23:22 UTC
Check if SharePoint site exists > Set SiteExists variable:

InvalidTemplate. Unable to process template language expressions in action 'Set_SiteExists_variable' inputs at line '1' and column '3759': 'The template language function 'bool' was invoked with a parameter that is not valid. The value cannot be converted to the target type.'.

**Comment by neimadpc** [comment] 2020-05-19 23:28
The expression is:
bool(body('Get_site_exists_job_output'))

**Comment by alexc-MSFT** [comment] 2020-05-20 08:59
@neimadpc please can you check the run history for the 'CheckSiteExists' runbook in Azure Automation. 

If you see a 403 error there then you are missing a step from the deployment instructions which was just added yesterday.

This is the part where you register the Azure AD app as a SharePoint add-in.

**Comment by neimadpc** [comment] 2020-05-20 11:12
> @neimadpc please can you check the run history for the 'CheckSiteExists' runbook in Azure Automation. 
> 
> 
> 
> If you see a 403 error there then you are missing a step from the deployment instructions which was just added yesterday.
> 
> 
> 
> This is the part where you register the Azure AD app as a SharePoint add-in. 

Hi, the previous step completed, status 200.

**Comment by LeeDrinkwater** [comment] 2020-05-20 11:50
Hello @alexc-MSFT 

First of all thanks for publishing this app. The timing is very good with a project I am working on where this functionality will be welcomed!

I ran into a similar problem to the above where the SetSiteExists variable fails with the same error that @neimadpc saw. I did register the SharePoint Add-In so looking at the CheckSiteExists runbook mine is failing with the following:

An error occured: Cannot bind argument to parameter 'AppId' because it is null. + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

Can you please help point me in the direction where I need to set this missing ID? I've checked the logic app is calling the correct client ID and secret. Is there somewhere else the AppID needs to be set?

**Comment by neimadpc** [comment] 2020-05-20 12:23
> > @neimadpc please can you check the run history for the 'CheckSiteExists' runbook in Azure Automation.
> > If you see a 403 error there then you are missing a step from the deployment instructions which was just added yesterday.
> > This is the part where you register the Azure AD app as a SharePoint add-in.
> 
> Hi, yes thanks. I saw it completed but missed the error:
> 
> An error occured: Token request failed. + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
> 
> I'll redo the SP add-on and try again. Not seeing a 403 error. Previous step "Get site exists job output" returned status 200.

@alexc-MSFT 
My issue is resolved. I had to grab the secret from the variable in logic app and update the variable in the automation account, now it runs. I expect it's from having to run the deploy script a few times while resolving other issues initially. - thanks!

**Comment by LeeDrinkwater** [comment] 2020-05-20 12:50
> utomation accou

@neimadpc Can you please advise if you needed to make any adjustments to the AppClientId variable as well as the appSecret? Mine is showing $null as the value and I am guessing this may be the reason mine is still failing but I cannot set this variable value so I don't know where it gets the value.

![image](https://user-images.githubusercontent.com/24454211/82447743-9f859c80-9aa0-11ea-986b-7846a65ec0cc.png)

**Comment by neimadpc** [comment] 2020-05-20 13:10
> > utomation accou
> 
> @neimadpc Can you please advise if you needed to make any adjustments to the AppClientId variable as well as the appSecret? Mine is showing $null as the value and I am guessing this may be the reason mine is still failing but I cannot set this variable value so I don't know where it gets the value.
> 
> ![AppID](https://user-images.githubusercontent.com/24454211/82447983-fa1ef880-9aa0-11ea-8c2f-f08c63cfc476.JPG)

@LeeDrinkwater  I did not have to make any changes there.. but my app ID is populated in the automation account variable, appClientId.

Are you sure your app is created in Azure app registrations? if there, you can grab the app ID and populate the variable.

**Comment by LeeDrinkwater** [comment] 2020-05-20 13:22
> utomation accou
> 
> @neimadpc Can you please advise if you needed to make any adjustments to the AppClientId variable as well as the appSecret? Mine is showing $null as the value and I am guessing this may be the reason mine is still failing but I cannot set this variable value so I don't know where it gets the value.
> 
> 
> @LeeDrinkwater  I did not have to make any changes there.. but my app ID is populated in the automation account variable, appClientId.
> Are you sure your app is created in Azure app registrations? if there, you can grab the app ID and populate the variable.

No mine is fixed at $null and won't let me modify it. The app did register which I can see under app registrations with a clientID and secret. I've modified the powershell with a new variable for the clientID which now works but presents me with another issue with "failed to obtain token" so I am getting somewhere! There must have been an issue with the deployment of the Azure logic app so I might remove the resource group and re-create from the script once again.

**Comment by alexc-MSFT** [comment] 2020-05-20 13:38
@LeeDrinkwater I would re-run the script again. I'm not quite sure how the appClientId variable has been set to null, this is generated by the script when the app is created and the variable has set.

The only thing I can think is that there must have been an issue when the script was run.

That being said, you should be able to edit that variable.

If not, just delete the variable and create another with the same name. As long as the name is the same and the value contains the App Id then you should be ok.

**Comment by alexc-MSFT** [comment] 2020-05-20 13:39
> > > @neimadpc please can you check the run history for the 'CheckSiteExists' runbook in Azure Automation.
> > > If you see a 403 error there then you are missing a step from the deployment instructions which was just added yesterday.
> > > This is the part where you register the Azure AD app as a SharePoint add-in.
> > 
> > 
> > Hi, yes thanks. I saw it completed but missed the error:
> > An error occured: Token request failed. + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
> > I'll redo the SP add-on and try again. Not seeing a 403 error. Previous step "Get site exists job output" returned status 200.
> 
> @alexc-MSFT
> My issue is resolved. I had to grab the secret from the variable in logic app and update the variable in the automation account, now it runs. I expect it's from having to run the deploy script a few times while resolving other issues initially. - thanks!

Glad you got it sorted, there must have been an issue with the script execution. 

@LeeDrinkwater I will keep this issue open for you but once solved I will close it out.

**Comment by LeeDrinkwater** [comment] 2020-05-20 14:05
> @LeeDrinkwater I would re-run the script again. I'm not quite sure how the appClientId variable has been set to null, this is generated by the script when the app is created and the variable has set.
> The only thing I can think is that there must have been an issue when the script was run.
> That being said, you should be able to edit that variable.
> If not, just delete the variable and create another with the same name. As long as the name is the same and the value contains the App Id then you should be ok.

Ok the APP ID issue is resolved. I now have a token generation exception so have a few questions please to help understand what is going on: as the app is registered in Azure AD and has been trusted as a SharePoint Add-In:

- The ServiceAccount was created and setup during script execution. Do I need to give this account any specific permissions apart from a Teams licence?

- If I use the test pane within the CheckSiteExists runbook I am receiving "token request failed" error. Is this running under the credentials of the user logged into the Azure portal or the ServiceAccount?

There is an additional error within this runbook. Is it of any concern?

Exception calling "Substring" with "2" argument(s): "Length cannot be less than zero.
Parameter name: length"
At line:12 char:1
+ $tenantName = $siteUrl.Substring(0, $siteUrl.IndexOf(".")).Replace("h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

**Comment by LeeDrinkwater** [comment] 2020-05-20 16:27
This is now resolved. Thanks for the assistance.

**Comment by alexc-MSFT** [comment] 2020-05-20 20:59
@LeeDrinkwater good to here the issue is resolved - I will close this now.

**Closed by alexc-MSFT** 2020-05-20 20:59 UTC
