### ISSUE TITLE
Beta logic app still using runbook

### ISSUE THREAD

**Issue by alexc-MSFT** [OfficeDev/microsoft-teams-apps-requestateam#196] opened 2020-11-06 10:16 UTC
The beta logic app 'ProcessTeamRequestBeta' is still configured to use the older runbook model when checking for existing SPO sites. This means this logic app will not work.

It needs updating to use the new CheckSiteExists logic app.

**Comment by PerOve** [comment] 2020-11-21 11:25
I tested this yesterday and got an error.
Steps: 
I followed the instructions in the Deployment Guide.
Then opening the logic app, changing the SharePoint site and click save.
I cannot save due to an error: "There is still connectors that is not authorized..." or something like that.

I found the error. And it is related to this change.
The logic app still has references to azureautomation in the json file. It must be removed.
Then all is good!

**Comment by PerOve** [comment] 2020-11-21 15:15
I deleted a comment since I found out it was the same as this fix actually fixes. I see the solution is not merged yet, I can confirm the problem is still there on todays master branch.

**Closed** 2020-12-03 15:54 UTC
Labels: bug, complete, functionality
